//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWA_Proyecto2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aterrizaje
    {
        public int Id { get; set; }
        public string DespegueId { get; set; }
        public Nullable<System.DateTime> FechaHoraRetorno { get; set; }
        public Nullable<bool> AvionPerdido { get; set; }
        public Nullable<bool> PerdidasHumanas { get; set; }
        public Nullable<bool> NecesitaRescate { get; set; }
    
        public virtual Despegue Despegue { get; set; }
    }
}
