//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWA_Proyecto2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despegue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Despegue()
        {
            this.Aterrizaje = new HashSet<Aterrizaje>();
        }
    
        public string NumeroDespegue { get; set; }
        public Nullable<System.DateTime> FechaHoraInicia { get; set; }
        public string TecnicoEncargado { get; set; }
        public string NombreMision { get; set; }
        public string NombrePiloto { get; set; }
        public Nullable<int> AvionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aterrizaje> Aterrizaje { get; set; }
    }
}
