//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWA_Proyecto2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetiroAviones
    {
        public int RetiroId { get; set; }
        public string NumeroSerie { get; set; }
        public string TecnicoRetiro { get; set; }
        public Nullable<System.DateTime> FechaRetiro { get; set; }
        public string MotivoRetiro { get; set; }
    }
}
